// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzpogg4MU66DaDWgf3PRYbSqhnEU5mc_0',
    appId: '1:198096055061:web:6a834b9be256d7208dd71c',
    messagingSenderId: '198096055061',
    projectId: 'scopetik-com',
    authDomain: 'scopetik-com.firebaseapp.com',
    storageBucket: 'scopetik-com.appspot.com',
    measurementId: 'G-VL8LQRLZX3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyTK29k5MC_5PyPxreXdn-1Y01OU-iSaE',
    appId: '1:198096055061:android:cf41bb8518983c758dd71c',
    messagingSenderId: '198096055061',
    projectId: 'scopetik-com',
    storageBucket: 'scopetik-com.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjvlwOSBM1LZ6oZP9kYZ6vCMlTZCP1ESE',
    appId: '1:198096055061:ios:b368f2d6c539a2ec8dd71c',
    messagingSenderId: '198096055061',
    projectId: 'scopetik-com',
    storageBucket: 'scopetik-com.appspot.com',
    iosClientId: '198096055061-9jq46g5grh87hkm4i5nnb96o8f3scq76.apps.googleusercontent.com',
    iosBundleId: 'com.example.scopetik',
  );
}
